services:
  app:
    environment:
      NEXTAUTH_URL: https://inventory.artech.tools
    networks:
      caddy:
        aliases: [inventory]
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

networks:
  caddy:
    external: true
